name: Build Godot Project

on:
  push:
    branches:
      - develop
      - main
  workflow_dispatch:

jobs:
  build:
    name: Export Godot Project
    runs-on: windows-latest

    steps:
      # Paso 1: Clonar el repo
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      # Paso 2: Exportar con Godot
      - name: Export with Godot
        uses: firebelley/godot-export@v7.0.0
        with:
          godot-version: '4.5.1-stable'
          export-presets: './export_presets.cfg'
          preset: 'Windows Desktop'
          output-dir: 'build'
          export-path: 'build/DontLookBackBeta.exe'
          template-download: true
          debug: false

      # Paso 3: Debug - listar contenido de build
      - name: List build folder
        run: |
          echo "Contenido del directorio actual:"
          dir
          echo "Contenido de build:"
          dir build

      # Paso 4: Crear zip del build
      - name: Create zip of build
        run: |
          echo "Creando carpeta artifacts..."
          mkdir artifacts
          echo "Comprimiendo build en artifacts/windows-build.zip"
          powershell -Command "Compress-Archive -Path 'build\*' -DestinationPath 'artifacts/windows-build.zip' -Force"
          echo "Contenido de artifacts:"
          dir artifacts

      # Paso 5: Subir artifact
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: artifacts/windows-build.zip

